# AI-Powered Customer Retention Intelligence Platform

## Notebook 1: Project Setup & Data Understanding

### Project Objective
The objective of this notebook is to understand the structure, quality, and business meaning of the customer churn dataset before building any machine learning model.

This phase focuses on:
- Loading the dataset
- Inspecting the data structure
- Understanding each column
- Checking missing values
- Identifying duplicate records
- Reviewing categorical and numerical variables
- Creating an initial data quality assessment

---

## Business Context
Customer churn occurs when customers stop using a company's product or service. For telecommunications companies, churn directly affects recurring revenue, customer lifetime value, and business growth.

This project aims to build an AI-powered system that predicts customer churn and supports proactive retention strategies.

---

## Dataset Used
**Dataset:** IBM Telco Customer Churn Dataset  
**Industry:** Telecommunications  
**Target Variable:** `Churn`  
**Problem Type:** Binary Classification  

---

## Expected Output of This Notebook
By the end of this notebook, we should have:
- A clear understanding of the dataset
- Initial data quality findings
- A list of cleaning tasks needed
- A foundation for the next phase: Data Cleaning & Preprocessing

In [1]:
# ============================================================
# Import Required Libraries
# ============================================================

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

print("Libraries imported successfully.")

Libraries imported successfully.

In [4]:
# ============================================================
# Load Dataset
# ============================================================

from google.colab import files
import pandas as pd

uploaded = files.upload()

Saving WA_Fn-UseC_-Telco-Customer-Churn.csv to WA_Fn-UseC_-Telco-Customer-Churn.csv

In [7]:
# ============================================================
# Preview Dataset
# ============================================================

df = pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")

print(df.head())

   customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No
1  5575-GNVDE    Male              0      No         No      34          Yes
2  3668-QPYBK    Male              0      No         No       2          Yes
3  7795-CFOCW    Male              0      No         No      45           No
4  9237-HQITU  Female              0      No         No       2          Yes

      MultipleLines InternetService OnlineSecurity OnlineBackup  \
0  No phone service             DSL             No          Yes
1                No             DSL            Yes           No
2                No             DSL            Yes          Yes
3  No phone service             DSL            Yes           No
4                No     Fiber optic             No           No

  DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0               No          No          No              No  Month-to-month
1              Yes          No          No              No        One year
2               No          No          No              No  Month-to-month
3              Yes         Yes          No              No        One year
4               No          No          No              No  Month-to-month

  PaperlessBilling              PaymentMethod  MonthlyCharges TotalCharges  \
0              Yes           Electronic check           29.85        29.85
1               No               Mailed check           56.95       1889.5
2              Yes               Mailed check           53.85       108.15
3               No  Bank transfer (automatic)           42.30      1840.75
4              Yes           Electronic check           70.70       151.65

  Churn
0    No
1    No
2   Yes
3    No
4   Yes

# 1. Dataset Overview

The first step in every data science project is to understand the dataset. This section provides an overview of the IBM Telco Customer Churn dataset, including its size, structure, data types, and target variable.

Understanding the data allows us to identify potential data quality issues and prepare an effective preprocessing strategy before training any machine learning models.

In [8]:
# ============================================================
# Dataset Dimensions
# ============================================================

print("="*60)
print("DATASET DIMENSIONS")
print("="*60)

print(f"Number of Rows    : {df.shape[0]:,}")
print(f"Number of Columns : {df.shape[1]}")

============================================================
DATASET DIMENSIONS
============================================================
Number of Rows    : 7,043
Number of Columns : 21

# 2. First Five Records

Previewing the first few records helps verify that the dataset has been loaded correctly and provides an initial understanding of the available variables.

In [9]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

# 3. Dataset Information

This section examines the data structure, including data types, non-null values, and memory usage. It helps identify columns that may require type conversion or additional preprocessing.

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [11]:
print("="*60)
print("DATA TYPES")
print("="*60)

df.dtypes

============================================================
DATA TYPES
============================================================

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

# 4. Statistical Summary

Generate descriptive statistics for numerical variables to understand their distribution, central tendency, and variability.

In [12]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
SeniorCitizen,7043.0,0.162147,0.368612,0.00,0.0,0.00,0.00,1.00
tenure,7043.0,32.371149,24.559481,0.00,9.0,29.00,55.00,72.00
MonthlyCharges,7043.0,64.761692,30.090047,18.25,35.5,70.35,89.85,118.75

In [13]:
df.describe(include="object").T

#Statistical Summary for Categorical Variables

                 count unique               top  freq
customerID        7043   7043        3186-AJIEK     1
gender            7043      2              Male  3555
Partner           7043      2                No  3641
Dependents        7043      2                No  4933
PhoneService      7043      2               Yes  6361
MultipleLines     7043      3                No  3390
InternetService   7043      3       Fiber optic  3096
OnlineSecurity    7043      3                No  3498
OnlineBackup      7043      3                No  3088
DeviceProtection  7043      3                No  3095
TechSupport       7043      3                No  3473
StreamingTV       7043      3                No  2810
StreamingMovies   7043      3                No  2785
Contract          7043      3    Month-to-month  3875
PaperlessBilling  7043      2               Yes  4171
PaymentMethod     7043      4  Electronic check  2365
TotalCharges      7043   6531                      11
Churn             7043      2                No  5174

# 5. Missing Values Analysis

Missing values can negatively impact machine learning models. This section identifies columns containing missing or incomplete information.

In [14]:
missing = df.isnull().sum()

missing = pd.DataFrame({
    "Column": missing.index,
    "Missing Values": missing.values,
    "Percentage": (missing.values / len(df))*100
})

missing

              Column  Missing Values  Percentage
0         customerID               0         0.0
1             gender               0         0.0
2      SeniorCitizen               0         0.0
3            Partner               0         0.0
4         Dependents               0         0.0
5             tenure               0         0.0
6       PhoneService               0         0.0
7      MultipleLines               0         0.0
8    InternetService               0         0.0
9     OnlineSecurity               0         0.0
10      OnlineBackup               0         0.0
11  DeviceProtection               0         0.0
12       TechSupport               0         0.0
13       StreamingTV               0         0.0
14   StreamingMovies               0         0.0
15          Contract               0         0.0
16  PaperlessBilling               0         0.0
17     PaymentMethod               0         0.0
18    MonthlyCharges               0         0.0
19      TotalCharges               0         0.0
20             Churn               0         0.0

In [15]:
duplicates = df.duplicated().sum()

print(f"Duplicate Records: {duplicates}")

#Duplicate Records

Duplicate Records: 0

In [16]:
unique = pd.DataFrame({
    "Column": df.columns,
    "Unique Values": [df[col].nunique() for col in df.columns]
})

unique

#Unique Values

              Column  Unique Values
0         customerID           7043
1             gender              2
2      SeniorCitizen              2
3            Partner              2
4         Dependents              2
5             tenure             73
6       PhoneService              2
7      MultipleLines              3
8    InternetService              3
9     OnlineSecurity              3
10      OnlineBackup              3
11  DeviceProtection              3
12       TechSupport              3
13       StreamingTV              3
14   StreamingMovies              3
15          Contract              3
16  PaperlessBilling              2
17     PaymentMethod              4
18    MonthlyCharges           1585
19      TotalCharges           6531
20             Churn              2

In [17]:
print(df.columns.tolist())

# Column Names

['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn']

# 6. Data Quality Assessment

Based on the initial inspection, we summarize the overall quality of the dataset and identify preprocessing tasks required before model development.

In [18]:
quality = pd.DataFrame({
    "Column": df.columns,
    "Data Type": df.dtypes.values,
    "Missing": df.isnull().sum().values,
    "Unique": [df[col].nunique() for col in df.columns]
})

quality

              Column Data Type  Missing  Unique
0         customerID    object        0    7043
1             gender    object        0       2
2      SeniorCitizen     int64        0       2
3            Partner    object        0       2
4         Dependents    object        0       2
5             tenure     int64        0      73
6       PhoneService    object        0       2
7      MultipleLines    object        0       3
8    InternetService    object        0       3
9     OnlineSecurity    object        0       3
10      OnlineBackup    object        0       3
11  DeviceProtection    object        0       3
12       TechSupport    object        0       3
13       StreamingTV    object        0       3
14   StreamingMovies    object        0       3
15          Contract    object        0       3
16  PaperlessBilling    object        0       2
17     PaymentMethod    object        0       4
18    MonthlyCharges   float64        0    1585
19      TotalCharges    object        0    6531
20             Churn    object        0       2

# Notebook Summary

This notebook introduced the IBM Telco Customer Churn dataset and performed an initial assessment of its structure and quality.

Key activities completed:

- Loaded the dataset successfully.
- Explored the dataset dimensions.
- Reviewed the first five records.
- Examined data types and dataset structure.
- Generated descriptive statistics.
- Assessed missing values and duplicate records.
- Evaluated column uniqueness and overall data quality.

The findings from this notebook will guide the next phase of the project, where the dataset will be cleaned, transformed, and prepared for exploratory data analysis and machine learning.